## docker compose up -d
#version: '3'
#
#services:
#  mysql:
#    image: mysql:latest
#    container_name: umcstudy
#    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: root1234!
#      MYSQL_DATABASE: umcstudy
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"

version: '3'
services:
  springboot-app:
    image: seheon/beanstalk-docker
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
