# docker compose up -d
version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: umcstudy
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: umcstudy
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    image: "docker.io/seheon/beanstalk-docker:latest"
    ports:
      - "80:8080"
    restart: "always"
