spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umcstudy
    username: root
    password: root1234!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false # hibernate 로그 남길지

logging:
  level:
    org.hibernate.SQL: OFF

jwt:
  secret: "dkqorhvmekgkwlaksdltlrksdpanjfajrdmausdksehlrpTwlckawk"
  token:
    access-expiration-time: 99999999
    refresh-expiration-time: 99999999

# Redis 설정
redis:
  host: 0.0.0.0
  port: 6379
